### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by jonslack22** [jonslack22/First-Agile-Project---follow-along#5]
As a {Love Running member} I can {submit a comment alongside my poll answer} so that {I can communicate something that selectable answers in a poll cannot capture}

# Acceptance Criteria
#### Acceptance Criteria 3:

# Tasks

- [ ] Task 1 - Create an input field for typing text-based characters
- [ ] Task 2 - Ensure the submit button 'submits' information contained within the input field
- [ ] Task 3 - Communicate that #1: their information is being submitted, and #2 the information submission is complete
- [ ] Task 4 - Allow site-administrators to see information submitted from the input field.
