### ISSUE TITLE
USER STORY: Anonymity in polls

### ISSUE THREAD

**Issue by jonslack22** [jonslack22/First-Agile-Project---follow-along#6]
As a {user} I can {submit information in a poll anonymously} so that {I can keep my identity hidden.}

# Acceptance Criteria
#### Acceptance Criteria 3: The option should be easily visible

# Tasks

- [ ] Task 1 - Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Task 2 - Create a new field in the model to track the username
- [ ] Task 3 - Update the controller function
- [ ] Task 4 - Test the functionality
