### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by jonslack22** [jonslack22/First-Agile-Project---follow-along#7]
As a {site administrator} I can {set an expiry date on a poll} so that {I can automatically hide a poll at a certain time}

# Acceptance Criteria
#### Acceptance Criteria 3: The administrator expiry date should be 4 days after the current date

# Tasks

- [ ] Task 1 - Update the admin module view using HTML and CSS to include a date picker
- [ ] Task 2 - Update the website view with the 'Stay tuned for another poll soon' message
- [ ] Task 3 - Use JavaScript function to validate the expiry date is at least after 4 days
- [ ] Task 4 - Create code for checking expired polls every day at 11:59PM and hide them

**Comment by jonslack22** [comment]
This is completed
